---
- name: List AWS resources
  hosts: localhost
  gather_facts: no

  tasks:
  - name: List instances
    amazon.aws.ec2_instance_info:
      filters:
        "instance-state-name": "running"
        "tag:Environment": "dev"
    register: instances
    
  - name: List security groups
    amazon.aws.ec2_security_group_info:
      filters:
        "group-name": "my-sg"
        "tag:Environment": "dev"
    register: security_groups

  - name: List S3 buckets
    amazon.aws.s3_bucket_info:
    register: s3_buckets

  - name: Print results
    debug:
      msg: "Instances: {{ instances.instances | json_query('*.InstanceId') }}"
      verbosity: 0

  - name: Print results
    debug:
      msg: "Security groups: {{ security_groups.security_groups | json_query('*.GroupId') }}"
      verbosity: 0

  - name: Print results
    debug:
      msg: "S3 buckets: {{ s3_buckets.buckets | json_query('*.Name') }}"
      verbosity: 0
