---
- name: List AWS resources
  hosts: localhost
  gather_facts: no

  tasks:
  - name: List instances
    amazon.aws.ec2_instance_info:
      filters:
        "instance-state-name": "running"
        "tag:Environment": "dev"
    register: instances
    
  - name: List security groups
    amazon.aws.ec2_security_group_info:
      filters:
        "group-name": "my-sg"
        "tag:Environment": "dev"
    register: security_groups

  - name: List S3 buckets
    amazon.aws.s3_bucket_info:
    register: s3_buckets

  - name: Print results
    debug:
      var: instances.instances | json_query('*.InstanceId')
      stdout_lines: yes

  - name: Print results
    debug:
      var: security_groups.security_groups | json_query('*.GroupId')
      stdout_lines: yes

  - name: Print results
    debug:
      var: s3_buckets.buckets | json_query('*.Name')
      stdout_lines: yes
