---
- name: Installer Apache sur les serveurs
  hosts: webapache
  become: yes
 
  tasks:
    - name: Installer le paquet Apache
      apt:
        name: apache2
        state: present
        update_cache: yes
 
    - name: S'assurer qu'Apache est démarré et activé au démarrage
      service:
        name: apache2
        state: started
        enabled: yes
