---
- name: Install and configure MariaDB
  hosts: localhost
  become: yes
 
  tasks:
  - name: Install MariaDB
    apt:
      name: mariadb-server
      state: present
 
  - name: Start MariaDB service
    service:
      name: mariadb
      state: started
      enabled: yes
 
  - name: Set MariaDB root password
    mysql_user:
      name: root
      password: root
      check_implicit_admin: yes
      login_unix_socket: /var/lib/mysql/mysql.sock
    become: yes
    become_method: sudo
 
  handlers:
  - name: restart mariadb
    service:
      name: mariadb
      state: restarted
