---
- name: Lancer des instances EC2 et configurer des buckets S3
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Lancer une instance EC2
      amazon.aws.ec2_instance:
        key_name: access-key
        instance_type: t2.micro
        image: ami-064519b8c76274859
        wait: yes
        region: us-east-1
        count: 1
        vpc_subnet_id: subnet-0718123ab0ec38a9d
        assign_public_ip: yes
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
      register: ec2

    - name: Afficher l'ID de l'instance
      debug:
        msg: "Instance ID: {{ ec2.instance_ids }}"

    - name: Créer un bucket S3
      aws_s3:
        bucket: bucket1
        mode: create
        region: us-east-1
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
